# Generated by Django 5.0.6 on 2024-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
