# Generated by Django 5.0.6 on 2024-05-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_ticket_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
